### ISSUE TITLE
Elaboração do referencial teórico: Bolhas financeiras - 28/02/2018

### ISSUE THREAD

**Issue by PedroBSB** [lamfo-unb/BubbleBitcoin#1]
@JuliaAkaishi a ideia é você escrever (em inglês) a parte do Referencial Teórico com respeito as bolhas financeiras. A discussão sobre bolhas comportamentais e estruturais. Por que o bitcoin pode ser uma bolha ? Você pode se basear nesse material de uma ex-aluna minha: http://bdm.unb.br/handle/10483/5230

**Comment by pengyaohao** [comment]
@JuliaAkaishi alguns artigos clássicos sobre bolhas pra você dar uma olhada:

- Flavin (1983)
- Diba & Grossman (1988)
- West (1986)
- Evans (1991)

Estudos de Bitcoin e bolhas:

- Sinha (2014)
- Godsiff (2015)
- Cheah & Fry (2015)
- Cheung, Roca & Su (2015)

**Comment by pengyaohao** [comment]
@JuliaAkaishi mais alguns...

- Wigniolle (2014)
- Michaelides, Tsionas & Konstantakis (2016)
- Bariviera, Basgalla, Hasperué & Naiouf (2017)

**Comment by PedroBSB** [comment]
Escreva aqui : https://www.overleaf.com/12805096rsjdmgrkdgvb @JuliaAkaishi
