### ISSUE TITLE
Elaboração do referencial teórico: Bolhas financeiras - 28/02/2018

### ISSUE THREAD

**Issue by PedroBSB** [lamfo-unb/BubbleBitcoin#2]
@patricktatagiba a ideia é você escrever (em inglês) a parte do Referencial Teórico com respeito a Self-organized criticality em finanças (https://en.wikipedia.org/wiki/Self-organized_criticality). Onde esses modelos foram usados em finanças ? Quais suas vantagens e limitações com respeito aos outros métodos de detecção de bolhas ? Você pode se basear nesse material de uma ex-aluna minha: http://bdm.unb.br/handle/10483/5230

**Comment by pengyaohao** [comment]
@patricktatagiba dê uma olhada na evolução do tema "econofísica" e como tem sido usado em finanças (complexidade, sistemas dinâmicos, modelos baseados em agentes). Apresente SOC como um
 tema particular em econofísica. Esses artigos podem ajudar:

- Chakraborti, Toke, Patriarca & Abergel (2011)
- Mantegna (2016)
- Schinckus (2016)

Faça também a conexão entre econofísica (com ênfase em SOC) e bolhas  financeiras. têm sido estudado. Dê uma olhada nos artigos publicados na "Physica A", provavelmente mandaremos pra lá. Priorize artigos de 2013 pra cá. Segue lista inicial:

- Andersen & Sornette (2004)
- Watanabe, Takayasu & Takayasu (2007)
- Cajueiro & Andrade (2010)
- Redelico & Proto (2012)
- Deviren, Kocakaplan, Keskin, Balcilar, Özdemir & Ersoy (2014)

**Comment by PedroBSB** [comment]
Escreva aqui : https://www.overleaf.com/12805096rsjdmgrkdgvb @patricktatagiba
